# Autogenerated wrapper script for ggml_jll for i686-linux-musl
export libggml

JLLWrappers.@generate_wrapper_header("ggml")
JLLWrappers.@declare_library_product(libggml, "libggml.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libggml,
        "lib/libggml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
